### ISSUE TITLE
Online nilm _ Window size 

### ISSUE THREAD

**Issue by ikrambennasrbennasr** [OdysseasKr/online-nilm#1]
Hello @OdysseasKr , 
-Does the choice of the window_size allow us to talk about real time disaggregation? 
-Can we say, more the size of the window is small, more we are close to the real time disaggregation phenomenon? 
-And if you have an idea, what's the shortest window size that we can use it in ShortSeq2Point model, to have a significant predictions? 
Thanks

**Comment by OdysseasKr** [comment]
Hi @ikrambennasrbennasr ,

1. I would say that almost any reasonable window_size is suitable for real-time disaggregation. The main concern is that a larger window_size leads to bigger inputs to the neural network. Thus the NN requires more memory and computation time to produce results. 
     Other than that, since we use overlapping windows, I don't see any reason why it wouldn't be used for online disaggregation.

2. I would say that the shorter the window, the lower the predictive power. A smaller window size definitely makes computation faster

3. "Significant predictions" depends a lot on the type of the predicted device, the complexity of the circuit etc. For the scenario that we assumed in this paper, the suggested window sizes were the ones that performed "sufficiently" well.

**Comment by ikrambennasrbennasr** [comment]
@OdysseasKr 
yes i see, thanks for your fast and helpful answers.
