### ISSUE TITLE
Unknown reasons lead to poor forecasting

### ISSUE THREAD

**Issue by guantongpeng** [OdysseasKr/online-nilm#11]
Hello, I used the code in GRUWithWindow (unchanged) to train on the UK-DALE data set for 20 epochs. The results on the test set and train set are as follows. Could you guide me what went wrong? If there have parameters need to be changed in the origin codes? My email is 1131618454@qq.com. Thank you!

test set result(house1):
============================== fridge ===============================
Recall: 0.7859230869169807
Precision: 0.41266457466402895
Accuracy: 0.5248407643312102
F1 Score: 0.5411746287350153
Relative error in total energy: 0.3398331663195207
Mean absolute error(in Watts): 52.944642146264606
============================== microwave ===============================
Recall: 0.0
Precision: nan
Accuracy: 0.9981933989577302
F1 Score: nan
Relative error in total energy: 0.9001037868715199
Mean absolute error(in Watts): 46.835767427785726
============================== dish_washer ===============================
Recall: 0.3579124579124579
Precision: 0.6814102564102564
Accuracy: 0.9721598147075854
F1 Score: 0.4693156732891832
Relative error in total energy: 0.24204084224869085
Mean absolute error(in Watts): 28.23636657077036
============================== kettle ===============================
Recall: 1.0
Precision: 0.003705848291835553
Accuracy: 0.003705848291835553
F1 Score: 0.007384331371870313
Relative error in total energy: nan
Mean absolute error(in Watts): nan
============================== washing_machine ===============================
Recall: 1.0
Precision: 0.014002820426241881
Accuracy: 0.014002820426241881
F1 Score: 0.027618898378124264
Relative error in total energy: 0.6725896530269214
Mean absolute error(in Watts): 45.197667568786486

train set result:
============================== fridge ===============================
Recall: 0.8107537507860929
Precision: 0.5566469799071689
Accuracy: 0.6309938560184221
F1 Score: 0.6600897844989165
Relative error in total energy: 0.22799071020177508
Mean absolute error(in Watts): 36.82874306859891
============================== microwave ===============================
Recall: 0.0
Precision: nan
Accuracy: 0.9844665012406948
F1 Score: nan
Relative error in total energy: 0.7793909745233287
Mean absolute error(in Watts): 26.616165471268648
============================== dish_washer ===============================
Recall: 0.28264518294729774
Precision: 0.34144363341443634
Accuracy: 0.9626699751861042
F1 Score: 0.3092745638200184
Relative error in total energy: 0.38819056995915857
Mean absolute error(in Watts): 28.17884941190762
============================== kettle ===============================
Recall: 1.0
Precision: 0.011702349402971742
Accuracy: 0.011702349402971742
F1 Score: 0.023133976924888156
Relative error in total energy: nan
Mean absolute error(in Watts): nan
============================== washing_machine ===============================
Recall: 1.0
Precision: 0.07855014895729891
Accuracy: 0.07855014895729891
F1 Score: 0.14565877911794495
Relative error in total energy: 0.2351688162192659
Mean absolute error(in Watts): 86.13717623592251

**Comment by qinxiaopang** [comment]
Have you fixed it? Share your methods pls.
