### ISSUE TITLE
Online data collection for prediction

### ISSUE THREAD

**Issue by dahurtados** [OdysseasKr/online-nilm#2]
Hi! 
How is the code set for online data collection?.
Regards.

**Comment by OdysseasKr** [comment]
Hello @dahurtados 
The code is not meant to be used for online data collection. It is a set of algorithms that can be used with a small amount of data that are fed in real-time. This means that there is no need for "future data" or lots of past data. 

You can find a more detailed explanation in the paper. Let me know if something is not clear.
