### ISSUE TITLE
could you please post the requirement if possible?

### ISSUE THREAD

**Issue by Hessen525** [OdysseasKr/online-nilm#3]
Hello,
Thanks for your repo, it give me so much help.
but when I call python gen.py ukdale.h5, it occured some errors. ( your neural-disaggregator is work well. ) Could you please post the requirement if possible?

Thanks!

**Comment by OdysseasKr** [comment]
That's a good suggestion, thanks! If you also have figured out the requirements, please share them.

**Comment by Engr-KhurramIqbal** [comment]
@Hessen525 
hello, will you please help to execute the "python gen.py" When I Call this file it shows error.If you know the error as  you confess in first comment. then pls help me to remove that ,thanks
