### ISSUE TITLE
May I have more detail about NeuralNILM data used for test in your project

### ISSUE THREAD

**Issue by Hessen525** [OdysseasKr/online-nilm#6]
Hi, 
In your project, You download test data from 
http://jack-kelly.com/files/neuralnilm/NeuralNILM_data.zip 
comment with "''' dataset of synthetic data from Neural NILM. 
Could you please give more detail about this dataset if possible? For example data_windows, and is that data with data augment described in Neural NILM?

**Comment by OdysseasKr** [comment]
Hello,

This dataset is used only for the testing part and was collected for Neural NILM. I would not be able to give you more information that what's in their paper.
