### ISSUE TITLE
Error loading data into memory

### ISSUE THREAD

**Issue by ZhuzengChu** [OdysseasKr/online-nilm#9]
Hi @OdysseasKr ,
Thank you for your paper so that I learned a lot of interesting things, I encountered a problem when the experiment was restored:
set up the project
meter = elec[conf["nilmtk_key"].encode("ascii")]  
File "E:\pycharms\ANACONDA\envs\neural\lib\site-packages\nilmtk\metergroup.py", line 296, in __getitem__
    raise TypeError()
I don't understand what this code means.
Thanks again, any reply and advice will be much appreciated!

**Comment by OdysseasKr** [comment]
Should be fixed now.
